# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Default Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'package.json'
  pull_request:
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build the forge
      run: npm run build
    - name: Test the forge
      run: npm run test
